### ISSUE TITLE
Mark all as read button

### ISSUE THREAD

**Issue by roland-d** [tomhunter-gh/SourceLog#18]
Hello Tom,

It would be nice to have a Mark all Read button as can be found in Commit Monitor.

P.s. Congrats on a useful tool. You ask for feedback on the frontpage but I don't see anywhere I can leave feedback.

**Comment by tomhunter-gh** [comment]
Hi Roland, thanks for the feedback!  Here's my email address: tom@unhandledexception.info (I've added this to the readme/frontpage now)

**Comment by tomhunter-gh** [comment]
Fixed in 674961d6c7a67ba6ba21e4829308ed808f7299c9.
