### ISSUE TITLE
Git & Mercurial plugin - fill Directory: with a "Browse..." button

### ISSUE THREAD

**Issue by SRombauts** [tomhunter-gh/SourceLog#35]
When Adding Subscription, it would be really helpfull to add a "Browse..." button to the "Directory" field

This would also help first time users to understand the configuration (ie. this is not an URL but a _local_ directory)

**Comment by tomhunter-gh** [comment]
Hi Sébastien, thanks a lot for trying the tool and for your suggestions.  Please could you try the latest version and let me know if the fixes work as expected?

Thanks,
Tom

**Comment by SRombauts** [comment]
Hi Tom, all this is nice and perfect, thanks a lot!

I am a regular user of CommitMonitor, but switching my projects to Git and was looking for a good solution.

Now, seeing that you take time to listen to you user I am sure this will become a "killer app" in a not so far future!

I will fill some more feature request when I will have some time for it.
But this will mainly be "please add this menu entry that I need/I am used to under Commit Monitor.

Nice work!
SRombauts
