### ISSUE TITLE
Access private repository

### ISSUE THREAD

**Issue by roland-d** [tomhunter-gh/SourceLog#41]
Hello Tom,

On Github I have access to a private repository, Sourcelog can't retrieve the log for this. Does it require a special URL to be used?

**Comment by tomhunter-gh** [comment]
Hi @roland-d, I think this would require enhancement to the GitHub plugin to use authentication..

In the meantime, could you create a local clone of the repository and use the Git plugin?

**Comment by roland-d** [comment]
The problem with a using a local clone would be that I would still need to manually update the repo, to get log messages. It's something that could work for now. What URL/path would I need to put into SL to do that?

**Comment by roland-d** [comment]
No longer needing this as I moved to Manjaro.
